- hosts: Production
  become: yes
  gather_facts: no
  tasks:
  - name: Create a Folder
    file:
     state: directory
     path: /home/ec2-user/hariom
     mode: 0755
     owner: ec2-user
     group: ec2-user
